---
- name: EOS Setup
  hosts: localhost

  tasks:
  - name: Test create VM
    os_server:
        state: present
        auth:
          auth_url: http://10.219.106.27:35357/v3/
          username: eosadmin
          password: Abcd.1234
          project_name: eoscloud
        name: ansvm2
        image: CentOS7
        security_groups: Linux-Generic
        key_name: EOSKEY
        availability_zone: OR1
        timeout: 300
        flavor: e91a07e2-8f9a-4f4b-830d-db8f64fd4141
        nics:
          - net-name: provider
        meta:
          hostname: ansvm2
          group: k8s

