---
- name: EOS Setup
  hosts: localhost
  vars:
    cluster_name: eos-zpn-k8s-os

  tasks:

  - name: K8s create VM
    register: jaja0
    os_server:
        state: present
        auth:
          auth_url: http://10.219.106.27:35357/v3/
          username: eosadmin
          password: Abcd.1234
          project_name: eoscloud
        name: jaja0
        config_drive: yes
        image: ClearLinux26430
        security_groups: Linux-Generic
        key_name: EOSKEY
        timeout: 300
        flavor: 10
        network: provider
        meta:
          hostname: jaja0
          group: k8s



- name: Register IP Addresses
  hosts: localhost
  tasks:
    - debug: 
        msg: >
           Report 
           
           
           {{ jaja0.openstack.accessIPv4 }}
            
           
